const indianStatesAndUTs = [
    'Andaman and Nicobar Islands',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chandigarh',
    'Chhattisgarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'New Delhi',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Lakshadweep',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Puducherry',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Others',
  ];
  
  const statusOptions = [
    'Cured',
    'Lapsed due to Cure',
    'Lapsed due to Money Issue',
    'Lapsed due to no Result',
    'Only one Timers',
    'Improvement',
    'New',
    'Regular',
    'Intermittent',
    'Others',
  ];
  
  const educationLevels = [
    'Toddler',
    'Up to 5th',
    'Up to 10th',
    'Up to 12th',
    'Undergraduate',
    'Graduation',
    'Post Graduation',
    'Others',
  ];
  

  const PatientRefrenceList = [
  'Husband',
  'Wife',
  'Daughter',
  'Son',
  'Father',
  'Mother',
  'Family',
  'Extended Family',
  'Relatives',
  'Colleagues',
  'Aquenties',
  'Doctor',
  'Others',
  ]

  const RefrenceList = [
"Patient",
"Google",
"Facebook",
"Whatsapp",
"Clinic Board",
"Seminar",
"Practo",
"Doctor",
"Staff",
"Medical Stores",
"Venkates",
"Dr. Shital",
"Instagram",
"LinkedIn",
"Google My Business",
"Google Call",
"Google Message",
"Clinic Visit",
"Website",
"Website Form",
  ]

  export {statusOptions, educationLevels, indianStatesAndUTs, PatientRefrenceList, RefrenceList}